added basic redux
ihsan-project/ihsanReactNative pull request #20
Opened 2021-03-21 19:02 UTC by bvajhi

In this PR I added basic redux structure

2021-03-22 02:34 UTC, mmislam101 requested changes
Functionally looks good. But please fix lint errors

2021-04-01 22:59 UTC, ahmednkhan24 submitted a review, later dismissed

2021-04-01 23:23 UTC, ahmednkhan24 approved these changes
:)

2021-04-02 00:27 UTC, mmislam101 approved these changes
👍

2021-04-02 23:58 UTC, merged