Axios GET /settings
ihsan-project/IhsanReactNative pull request #35
Opened 2021-04-26 04:33 UTC by mmislam101

Leaving remaining cleanup to: https://github.com/ihsan-project/IhsanReactNative/issues/7

Run the `yarn setup` command with all the keys to download a new version of the `.env` file that has the correct keys.

2021-04-29 03:46 UTC, ahmednkhan24 requested changes

2021-04-29 18:47 UTC, mmislam101 commented on package.json
> +    "react-native-axios": "^0.17.1",
Yah good point. I'll look into using axios directly

2021-04-29 18:48 UTC, mmislam101 commented on src/sagas/appSagas.ts
> +  });
Yes. I'm deferring that kind of work to https://github.com/ihsan-project/IhsanReactNative/issues/7

2021-04-30 01:34 UTC, mmislam101 commented on package.json
> +    "react-native-axios": "^0.17.1",
Fixed

2021-04-30 01:37 UTC, ahmednkhan24 approved these changes

2021-04-30 01:38 UTC, merged